CREATE DATABASE HelpDeskDB
GO

CREATE TABLE Customer (    Id INT IDENTITY(1,1) PRIMARY KEY,    FirstName NVARCHAR(30) NOT NULL,    LastName NVARCHAR (30) NOT NULL,    Email NVARCHAR (60) NOT NULL,	Phone NVARCHAR (15) NOT NULL,);